
version: '3'
services:

  db:
    image: postgres:14.7
    environment:
      - POSTGRES_DB=javalibrary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:9.8.1
    command: -url=jdbc:postgresql://db:5432/javalibrary -user=postgres -password=postgres migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.application.name=java-library-api
      - logging.level.root=INFO
      - logging.level.org.flywaydb=DEBUG

      #DB setup
      - spring.datasource.url=jdbc:postgresql://db:5432/javalibrary
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.format_sql=true

      #JWT
      - jwt.secret=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      - jwt.lifetime=30m
    ports:
      - "8080:8080"
    depends_on:
      - db
      - flyway

volumes:
  postgres-data: