CREATE TABLE book
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn        VARCHAR(255),
    name        VARCHAR(255),
    genre       VARCHAR(255),
    description VARCHAR(255),
    author      VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_isbn UNIQUE (isbn);